import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sync Audio with Lexical",
  description: "Generated by create next app",
  authors: [
    {
      name: "Muhammad Hassan",
      url: "https://www.linkedin.com/in/hassanprodeveloper",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ background: "#fff", color: "#000" }}
      >
        {children}
      </body>
    </html>
  );
}
